blank_issues_enabled: true
contact_links:
  - name: NITINDYT CLIENT LAUNCHER Issues
    url: https://github.com/NitindytClient/NitindytClient/issues
    about: Please search existing issues before opening a new one.
